# Generated by Django 3.0.5 on 2020-04-22 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('steet2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcartproduct',
            name='recipient_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_address', to='shopping_cart.Address'),
        ),
        migrations.AddField(
            model_name='shoppingcartproduct',
            name='return_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_address', to='shopping_cart.Address'),
        ),
    ]
