# Generated by Django 3.0.5 on 2020-04-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_shoppingcart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='session_key',
        ),
    ]
