# Generated by Django 3.0.5 on 2020-04-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_remove_shoppingcart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='message',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
