# Generated by Django 3.0.5 on 2020-04-22 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_auto_20200422_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='recipient_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_address', to='shopping_cart.Address'),
        ),
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='return_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_address', to='shopping_cart.Address'),
        ),
    ]
