# Generated by Django 3.0.5 on 2020-05-19 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url'),
        ('shopping_cart', '0005_auto_20200422_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_products',
            field=models.ManyToManyField(blank=True, through='shopping_cart.ShoppingCartProduct', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_products', to='shopping_cart.ShoppingCart'),
        ),
    ]
