# Generated by Django 3.0.5 on 2020-08-07 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_auto_20200807_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
