# Generated by Django 3.0.5 on 2020-08-19 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_cart', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('FULFILLED', 'FULFILLED'), ('CANCELED', 'CANCELED')], default='PAID', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=2500)),
                ('color', models.CharField(choices=[('BLACK', 'Black'), ('LIGHT_BLUE', 'LightBlue')], default='BLACK', max_length=50, null=True)),
                ('font', models.CharField(choices=[('REGULAR', 'Regular'), ('CURSIVE', 'Cursive')], default='CURSIVE', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('CANCELED', 'CANCELED')], default='PAID', max_length=10)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products_set', to='orders.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('recipient_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_recipient_address', to='shopping_cart.Address')),
                ('return_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_return_address', to='shopping_cart.Address')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(blank=True, through='orders.OrderProduct', to='products.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
