# Generated by Django 3.0.5 on 2020-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200612_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('LIGHT_BLUE', 'LightBlue')], default='BLACK', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='font',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('CURSIVE', 'Cursive')], default='CURSIVE', max_length=50, null=True),
        ),
    ]
