# Generated by Django 3.0.5 on 2020-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p_type', models.CharField(choices=[('CA', 'Card'), ('GI', 'Gift')], default='CA', max_length=2)),
                ('creator_name', models.CharField(max_length=50)),
            ],
        ),
    ]
